### ISSUE TITLE
add -y option for unattended install

### ISSUE THREAD

**Issue by tazihad** [nureon22/gfont#5]
trying to put this in my script. But it always ask for confirmation.
It would be better if 
```
gfont -y install fira-sans
```
works

**Comment by tazihad** [comment]
looks like
```
gfont install -y fira-sans
```
works, my bad.

**Comment by nureon22** [comment]
@tazihad `gfont` command itself doesn't accept `-y` option. You can view available subcommands and options with `gfont --help` or `gfont <subcommand> --help`.
